name: Deploy buy runner

on:
  push:
    branches: [ "master" ]

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        run: docker compose down

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose build
        run: docker build -t accountingoffunds .
      - name: docker compose
        run: docker compose up -d

  cleanup:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: prune images
        run: docker image prune -f
      - name: prune cache
        run: docker builder prune -f